### ISSUE TITLE
Thanks Chef xawex465!

### ISSUE THREAD

**Issue by rupert3k** [xawex465/LineageOS-16.0#1]
Grateful for your work, sadly I & one other was unable to boot yet it's very kind of you to make this available

**Comment by xawex465** [comment]
Hi,what device do you have s9? s9+?

**Comment by rupert3k** [comment]
An almost new S9

**Comment by xawex465** [comment]
try new build, flash csf2 vendor link- https://drive.google.com/open?id=1-j2MhxANgTa7WyTZIGLI5UEh7iSlSljv

**Comment by rupert3k** [comment]
No luck flashing vendor but dirty flash worked great, thanks!

**Comment by luck3rhoch3** [comment]
Which vendor do i need? ending up in a bootloop with both builds...

**Comment by xawex465** [comment]
latest vendor for 11.09 build, and for 27.10 build is needed csf2.
